class DataIngestionArtifact:
    pass
class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModelTrainerArtifact:...
class ModelEvalutionArtifact:...
class ModelPusherArtifact:...